# Generated by Django 6.0 on 2025-12-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='display_name',
            field=models.CharField(blank=True, help_text='What shows publicly (e.g., "Anonymous Angel", "Ada from Lagos")', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='giving_focus',
            field=models.JSONField(default=list, help_text='Preferred giving focus areas (e.g., ["education", "health"])'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='hear_about',
            field=models.CharField(blank=True, choices=[('search', 'Search Engine (Google, Bing, etc.)'), ('social', 'Social Media'), ('friend', 'Friend or Family'), ('news', 'News Article or Blog'), ('other', 'Other')], help_text='How did you hear about WishChain?', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Keep my contributions anonymous'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='show_display_name',
            field=models.BooleanField(default=False, help_text='Show my display name on wishes I grant'),
        ),
    ]
