# Generated by Django 6.0 on 2025-12-09 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WisherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_size', models.PositiveIntegerField(blank=True, null=True)),
                ('income_bracket', models.CharField(blank=True, choices=[('below_average', 'Below Average'), ('average', 'Average'), ('above_average', 'Above Average')], max_length=50, null=True)),
                ('id_document', models.FileField(blank=True, help_text='Upload a government-issued ID for verification', null=True, upload_to='id_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wisher_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_wishers', to='partners.partner')),
            ],
            options={
                'verbose_name': 'Wisher Profile',
                'verbose_name_plural': 'Wisher Profiles',
            },
        ),
    ]
